[package]
name = "ione"
version = "0.1.0"
edition = "2024"
description = "ione - lightweight code editor with an integrated PowerShell terminal"
authors = ["Zulkarnaen Syam Amansyah"]
license = "MIT"

[dependencies]
eframe = "0.36"
egui_code_editor = "0.3"
opener = "0.8"
egui_extras = { version = "0.36", features = ["svg"] }
resvg = "0.45"
rfd = "0.15"
image = "0.25"
portable-pty = "0.8"
vt100 = "0.16"
